name: Forward issue + PR activity to project board manager

on:
  issues:
    types: [opened, reopened, closed, labeled, unlabeled]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  id-token: write
  contents: read
  issues: read
  pull-requests: read

jobs:
  forward:
    runs-on: ubuntu-latest

    env:
      ENDPOINT_URL: "https://us-central1-project-board-manager.cloudfunctions.net/ingestGithubDataEvents"
      OIDC_AUDIENCE: "https://us-central1-project-board-manager.clo_
